doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: 'pdo_pgsql'
                server_version: '9.6'
                charset: utf8
                url: '%env(resolve:DATABASE_URL)%'
            cis:
                # configure these for your database server
                driver:   'pdo_pgsql'
                host:     '10.182.144.242'
                port:     '5432'
                dbname:   'sikkimhc_pg'
                user:     'postgres'
                password: ''
                charset:   utf8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Main'
                        prefix: 'App\Entity'
                        alias: Main
            cis:
                connection: cis
                mappings:
                    Customer:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/CIS'
                        prefix: 'App\Entity\CIS'
                        alias: cis