<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrcl8ux\srcProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrcl8ux/srcProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXrcl8ux.legacy');

    return;
}

if (!\class_exists(srcProdProjectContainer::class, false)) {
    \class_alias(\ContainerXrcl8ux\srcProdProjectContainer::class, srcProdProjectContainer::class, false);
}

return new \ContainerXrcl8ux\srcProdProjectContainer(array(
    'container.build_hash' => 'Xrcl8ux',
    'container.build_id' => '88c79344',
    'container.build_time' => 1536125426,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrcl8ux');
