<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAx8s9gx\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAx8s9gx/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAx8s9gx.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAx8s9gx\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerAx8s9gx\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Ax8s9gx',
    'container.build_id' => 'e4e0367f',
    'container.build_time' => 1536746807,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAx8s9gx');
